### ISSUE TITLE
java 层的hook会有问题

### ISSUE THREAD

**Issue by Caij** [Guolei1130/global_httpdns#1]
Android 8.0手机测试 
method.invoke(mOrigin, args) 
会出异常。

**Comment by Guolei1130** [comment]
```
        try {
            return method.invoke(mOrigin, args);
        } catch (InvocationTargetException e) {
            throw e.getCause();
        }
```

是说这里么。这个函数本身就是会异常的。你现在DNS解析有问题么？

**Comment by Caij** [comment]
对 那如果我不走自己的逻辑呢，  直接走系统的方法  还有这个类还有其他方法  那这个类的方法全都失效？

**Comment by Guolei1130** [comment]
[Os.java](https://android.googlesource.com/platform/libcore/+/android-cts-8.0_r11/luni/src/main/java/libcore/io/Os.java)

你可以看一下这个接口，绝大部分的方法throw 异常的

**Comment by Caij** [comment]
我就很奇怪  如果执行正常也会出这个异常吗，  还是内部执行出错了？

**Comment by Guolei1130** [comment]
我这里测试没有出现异常。

**Comment by Caij** [comment]
try {
            return method.invoke(mOrigin, args);
        } catch (InvocationTargetException e) {
            throw e.getCause();
        }

这个不会有InvocationTargetException 吗？

**Comment by Guolei1130** [comment]
@Caij  问题排查到了。以API 26的SDK 为例。解析是通过Inet6AddressImpl来实现的。

```
    @Override
    public InetAddress[] lookupAllHostAddr(String host, int netId) throws UnknownHostException {
        if (host == null || host.isEmpty()) {
            // Android-changed: Return both the Inet4 and Inet6 loopback addresses
            // when host == null or empty.
            return loopbackAddresses();
        }

        // Is it a numeric address?
        InetAddress result = InetAddress.parseNumericAddressNoThrow(host);
        if (result != null) {
            result = InetAddress.disallowDeprecatedFormats(host, result);
            if (result == null) {
                throw new UnknownHostException("Deprecated IPv4 address format: " + host);
            }
            return new InetAddress[] { result };
        }

        return lookupHostByName(host, netId);
    }
```

首先，第一步会以ip的形式去解析，也就是把StructAddrinfo的ai_flags设置为AI_NUMERICHOST
```
    static InetAddress parseNumericAddressNoThrow(String address) {
        // Accept IPv6 addresses (only) in square brackets for compatibility.
        if (address.startsWith("[") && address.endsWith("]") && address.indexOf(':') != -1) {
            address = address.substring(1, address.length() - 1);
        }
        StructAddrinfo hints = new StructAddrinfo();
        hints.ai_flags = AI_NUMERICHOST;
        InetAddress[] addresses = null;
        try {
            addresses = Libcore.os.android_getaddrinfo(address, hints, NETID_UNSET);
        } catch (GaiException ignored) {
        }
        return (addresses != null) ? addresses[0] : null;
    }
```

如果不是IP，却设置flag为AI_NUMERICHOST的情况下，铁定会异常，只不过framework里直接ignore了。
而在我们自己的invoke中，flag为AI_NUMERICHOST的情况下，是直接调用系统的DNS解析的。因此这里也会抛出一个GaiException。

**Comment by Caij** [comment]
非常感谢啊  我一直困惑这个问题是什么导致。  我之前采用的qq邮箱的hook方案, 但是如果能够hook这个， 处理上更加整洁。

**Comment by DrownCoder** [comment]
> @Caij 问题排查到了。以API 26的SDK 为例。解析是通过Inet6AddressImpl来实现的。
> 
> ```
>     @Override
>     public InetAddress[] lookupAllHostAddr(String host, int netId) throws UnknownHostException {
>         if (host == null || host.isEmpty()) {
>             // Android-changed: Return both the Inet4 and Inet6 loopback addresses
>             // when host == null or empty.
>             return loopbackAddresses();
>         }
> 
>         // Is it a numeric address?
>         InetAddress result = InetAddress.parseNumericAddressNoThrow(host);
>         if (result != null) {
>             result = InetAddress.disallowDeprecatedFormats(host, result);
>             if (result == null) {
>                 throw new UnknownHostException("Deprecated IPv4 address format: " + host);
>             }
>             return new InetAddress[] { result };
>         }
> 
>         return lookupHostByName(host, netId);
>     }
> ```
> 
> 首先，第一步会以ip的形式去解析，也就是把StructAddrinfo的ai_flags设置为AI_NUMERICHOST
> 
> ```
>     static InetAddress parseNumericAddressNoThrow(String address) {
>         // Accept IPv6 addresses (only) in square brackets for compatibility.
>         if (address.startsWith("[") && address.endsWith("]") && address.indexOf(':') != -1) {
>             address = address.substring(1, address.length() - 1);
>         }
>         StructAddrinfo hints = new StructAddrinfo();
>         hints.ai_flags = AI_NUMERICHOST;
>         InetAddress[] addresses = null;
>         try {
>             addresses = Libcore.os.android_getaddrinfo(address, hints, NETID_UNSET);
>         } catch (GaiException ignored) {
>         }
>         return (addresses != null) ? addresses[0] : null;
>     }
> ```
> 
> 如果不是IP，却设置flag为AI_NUMERICHOST的情况下，铁定会异常，只不过framework里直接ignore了。
> 而在我们自己的invoke中，flag为AI_NUMERICHOST的情况下，是直接调用系统的DNS解析的。因此这里也会抛出一个GaiException。

请问下这样有什么解决方法吗？
