### ISSUE TITLE
AKGetImageByName这个函数是哪里来的

### ISSUE THREAD

**Issue by Hujinyong** [Guolei1130/global_httpdns#2]
这个AK库是哪里来的，好像只有编译好的so
我想将这个库静态链接到我自己的so里

**Comment by Guolei1130** [comment]
不好意思这么久才看见，AK这个库是Lody写的，不过如果你想在线上使用这种方式，最好还是慎用！！！！！！！！ 一般而言，替换掉整个java层的DNS已经足够了
